/*
 * This source file was generated by the Gradle 'init' task
 */
package demo.app

import demo.list.LinkedList

import static demo.utilities.StringUtils.join
import static demo.utilities.StringUtils.split
import static demo.app.MessageUtils.getMessage

import org.apache.commons.text.WordUtils

class App {
    static void main(String[] args) {
        LinkedList tokens
        tokens = split(getMessage())
        String result = join(tokens)
        println(WordUtils.capitalize(result))
    }
}
