/*
 * This source file was generated by the Gradle 'init' task
 */
package demo.app

import groovy.transform.PackageScope

@PackageScope
class MessageUtils {
    static String getMessage() {
        return "Hello      World!"
    }
}
